### PR TITLE
Add romanian translation for device settings

### PR DESCRIPTION
**Pull request by ygorigor**

### CODE REVIEW

**Comment by ygorigor** [comment]
ping @daniml3

**Comment by danielml3** [comment]
Merged into arrow-12.1, will merge it into arrow-13.0 as soon as I verify that it works fine.

**Comment by ygorigor** [comment]
@daniml3 I use it on Arrow 13. Have no issues.

**Comment by ygorigor** [comment]
Screenshot_20220927-065042_Setări specifice dispozitivului

**Comment by danielml3** [comment]
Merged on arrow-13.0 branch.

**Pull request closed without merging**
